name: flutter_sticky_header
description: Flutter implementation of sticky header
version: 0.3.0
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/flutter_sticky_header

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <2.0.0"
